// market name to CoinMarketCap page
export const marketNameToPage: { [key: string]: string } = {
    BTC: 'bitcoin',
    ETH: 'ethereum',
    BNB: 'binance-coin',
    SOL: 'solana',
    UNI: 'uniswap',
    AAVE: 'aave',
    FTT: 'ftx-token',
    MKR: 'maker',
    COMP: 'compound',
    SUSHI: 'sushiswap',
    SNX: 'synthetix-network-token',
    YFI: 'yearn-finance',
    CRV: 'curve-dao-token',
    WOO: 'wootrade',
    SRM: 'serum',
    PERP: 'perpetual-protocol',
    '1INCH': '1inch',
    RAY: 'raydium',
    OXY: 'oxygen',
    SLRS: 'solrise-finance',
    ATLAS: 'star-atlas',
    POLIS: 'star-atlas-polis',
    EDEN: 'archer-dao-governance-token',
    DYDX: 'dydx',
}
